Name:           groff
Version:	1.22.4
Release:        1%{?dist}
Summary:	Text formatter used for man pages

License:	GPL-2
URL:		https://www.gnu.org/software/groff/groff.html
Source0:	https://ftpmirror.gnu.org/gnu/groff/groff-%{version}.tar.gz

#BuildRequires:
#Requires:

%description

%prep
%setup -q

%build
./configure --prefix=/usr --without-x
make

%install
rm -rf $RPM_BUILD_ROOT
%make_install
rm -rf $RPM_BUILD_ROOT/usr/share/info/dir

%files
/usr/bin/addftinfo
/usr/bin/afmtodit
/usr/bin/chem
/usr/bin/eqn
/usr/bin/eqn2graph
/usr/bin/gdiffmk
/usr/bin/glilypond
/usr/bin/gperl
/usr/bin/gpinyin
/usr/bin/grap2graph
/usr/bin/grn
/usr/bin/grodvi
/usr/bin/groff
/usr/bin/groffer
/usr/bin/grog
/usr/bin/grolbp
/usr/bin/grolj4
/usr/bin/gropdf
/usr/bin/grops
/usr/bin/grotty
/usr/bin/hpftodit
/usr/bin/indxbib
/usr/bin/lkbib
/usr/bin/lookbib
/usr/bin/mmroff
/usr/bin/neqn
/usr/bin/nroff
/usr/bin/pdfmom
/usr/bin/pdfroff
/usr/bin/pfbtops
/usr/bin/pic
/usr/bin/pic2graph
/usr/bin/post-grohtml
/usr/bin/pre-grohtml
/usr/bin/preconv
/usr/bin/refer
/usr/bin/roff2dvi
/usr/bin/roff2html
/usr/bin/roff2pdf
/usr/bin/roff2ps
/usr/bin/roff2text
/usr/bin/roff2x
/usr/bin/soelim
/usr/bin/tbl
/usr/bin/tfmtodit
/usr/bin/troff
/usr/lib/groff/glilypond/args.pl
/usr/lib/groff/glilypond/oop_fh.pl
/usr/lib/groff/glilypond/subs.pl
/usr/lib/groff/gpinyin/subs.pl
/usr/lib/groff/groff_opts_no_arg.txt
/usr/lib/groff/groff_opts_with_arg.txt
/usr/lib/groff/groffer/main_subs.pl
/usr/lib/groff/groffer/man.pl
/usr/lib/groff/groffer/split_env.sh
/usr/lib/groff/groffer/subs.pl
/usr/lib/groff/groffer/version.sh
/usr/lib/groff/grog/subs.pl
/usr/share/doc/groff-%{version}/examples/chem/122/README
/usr/share/doc/groff-%{version}/examples/chem/122/ch2a_ethyl.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch2b_benzene.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch2c_benzene_right.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4a_stick.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4b_methyl_acetate.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4c_colon.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4d_HCl.H2O.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4e_CaSO4.2H2O.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4f_C.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4g_BP.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4h_methacrylate.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4i_cyclo.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4j_ring4.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4k_ring3.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4l_vertex.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4m_double.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4n_triple.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4o_aromatic.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4p_cholestanol.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4q_rings.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4r_spiro.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4s_heteroatoms.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4t_polycyclic.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4u_nicotine.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4v_histidine.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4w_lsd.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4x_anisole.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4y_reserpine.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4z1_eqn_glutamic.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch4z2_text.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch5a_size.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch6a_pic.chem
/usr/share/doc/groff-%{version}/examples/chem/122/ch6b_dna.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAa_polymer.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAb_vinyl_chloro.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAc_morphine.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAd_chlorophyll.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAe_chair.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAf_arrow.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAg_circle.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAh_brackets.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chAi_poly_vinyl_chloride.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chBa_jump.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chBb_bonds.chem
/usr/share/doc/groff-%{version}/examples/chem/122/chBc_rings.chem
/usr/share/doc/groff-%{version}/examples/chem/README
/usr/share/doc/groff-%{version}/examples/chem/atp.chem
/usr/share/doc/groff-%{version}/examples/chem/cholesterin.chem
/usr/share/doc/groff-%{version}/examples/chem/ethamivan.chem
/usr/share/doc/groff-%{version}/examples/chem/lsd.chem
/usr/share/doc/groff-%{version}/examples/chem/morphine.chem
/usr/share/doc/groff-%{version}/examples/chem/penicillin.chem
/usr/share/doc/groff-%{version}/examples/chem/reserpine.chem
/usr/share/doc/groff-%{version}/examples/gnu.eps
/usr/share/doc/groff-%{version}/examples/grnexmpl.g
/usr/share/doc/groff-%{version}/examples/grnexmpl.me
/usr/share/doc/groff-%{version}/examples/grnexmpl.ps
/usr/share/doc/groff-%{version}/examples/groff.css
/usr/share/doc/groff-%{version}/examples/hdtbl/chess_board.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/chess_board.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/col_rowspan_colors.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/col_rowspan_colors.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/color_boxes.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/color_boxes.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/color_nested_tables.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/color_nested_tables.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/color_table_cells.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/color_table_cells.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/color_transitions.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/color_transitions.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/common.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/fonts_n.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/fonts_n.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/fonts_x.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/fonts_x.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/gnu.eps
/usr/share/doc/groff-%{version}/examples/hdtbl/mixed_pickles.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/mixed_pickles.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/rainbow.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/rainbow.roff
/usr/share/doc/groff-%{version}/examples/hdtbl/short_reference.ps
/usr/share/doc/groff-%{version}/examples/hdtbl/short_reference.roff
/usr/share/doc/groff-%{version}/examples/mm/letter.mm
/usr/share/doc/groff-%{version}/examples/mom/README-fr.txt
/usr/share/doc/groff-%{version}/examples/mom/README.txt
/usr/share/doc/groff-%{version}/examples/mom/elvis_syntax
/usr/share/doc/groff-%{version}/examples/mom/elvis_syntax.new
/usr/share/doc/groff-%{version}/examples/mom/letter.mom
/usr/share/doc/groff-%{version}/examples/mom/mom-pdf.mom
/usr/share/doc/groff-%{version}/examples/mom/mom.vim
/usr/share/doc/groff-%{version}/examples/mom/mon_premier_doc.mom
/usr/share/doc/groff-%{version}/examples/mom/penguin.pdf
/usr/share/doc/groff-%{version}/examples/mom/penguin.ps
/usr/share/doc/groff-%{version}/examples/mom/sample_docs.mom
/usr/share/doc/groff-%{version}/examples/mom/slide-demo.mom
/usr/share/doc/groff-%{version}/examples/mom/typesetting.mom
/usr/share/doc/groff-%{version}/examples/webpage.ms
/usr/share/doc/groff-%{version}/examples/webpage.ps
/usr/share/doc/groff-%{version}/html/mom/appendices.html
/usr/share/doc/groff-%{version}/html/mom/color.html
/usr/share/doc/groff-%{version}/html/mom/cover.html
/usr/share/doc/groff-%{version}/html/mom/definitions.html
/usr/share/doc/groff-%{version}/html/mom/docelement.html
/usr/share/doc/groff-%{version}/html/mom/docprocessing.html
/usr/share/doc/groff-%{version}/html/mom/goodies.html
/usr/share/doc/groff-%{version}/html/mom/graphical.html
/usr/share/doc/groff-%{version}/html/mom/headfootpage.html
/usr/share/doc/groff-%{version}/html/mom/images.html
/usr/share/doc/groff-%{version}/html/mom/inlines.html
/usr/share/doc/groff-%{version}/html/mom/intro.html
/usr/share/doc/groff-%{version}/html/mom/letters.html
/usr/share/doc/groff-%{version}/html/mom/macrolist.html
/usr/share/doc/groff-%{version}/html/mom/rectoverso.html
/usr/share/doc/groff-%{version}/html/mom/refer.html
/usr/share/doc/groff-%{version}/html/mom/reserved.html
/usr/share/doc/groff-%{version}/html/mom/stylesheet.css
/usr/share/doc/groff-%{version}/html/mom/tables-of-contents.html
/usr/share/doc/groff-%{version}/html/mom/toc.html
/usr/share/doc/groff-%{version}/html/mom/typesetting.html
/usr/share/doc/groff-%{version}/html/mom/using.html
/usr/share/doc/groff-%{version}/html/mom/version-2.html
/usr/share/doc/groff-%{version}/meintro.me
/usr/share/doc/groff-%{version}/meintro.ps
/usr/share/doc/groff-%{version}/meintro_fr.me
/usr/share/doc/groff-%{version}/meintro_fr.ps
/usr/share/doc/groff-%{version}/meref.me
/usr/share/doc/groff-%{version}/meref.ps
/usr/share/doc/groff-%{version}/pic.ms
/usr/share/doc/groff-%{version}/pic.ps
/usr/share/groff/%{version}/eign
/usr/share/groff/%{version}/font/devascii/B
/usr/share/groff/%{version}/font/devascii/BI
/usr/share/groff/%{version}/font/devascii/DESC
/usr/share/groff/%{version}/font/devascii/I
/usr/share/groff/%{version}/font/devascii/R
/usr/share/groff/%{version}/font/devcp1047/B
/usr/share/groff/%{version}/font/devcp1047/BI
/usr/share/groff/%{version}/font/devcp1047/DESC
/usr/share/groff/%{version}/font/devcp1047/I
/usr/share/groff/%{version}/font/devcp1047/R
/usr/share/groff/%{version}/font/devdvi/CW
/usr/share/groff/%{version}/font/devdvi/CWEC
/usr/share/groff/%{version}/font/devdvi/CWI
/usr/share/groff/%{version}/font/devdvi/CWIEC
/usr/share/groff/%{version}/font/devdvi/CWITC
/usr/share/groff/%{version}/font/devdvi/CWTC
/usr/share/groff/%{version}/font/devdvi/DESC
/usr/share/groff/%{version}/font/devdvi/EX
/usr/share/groff/%{version}/font/devdvi/HB
/usr/share/groff/%{version}/font/devdvi/HBEC
/usr/share/groff/%{version}/font/devdvi/HBI
/usr/share/groff/%{version}/font/devdvi/HBIEC
/usr/share/groff/%{version}/font/devdvi/HBITC
/usr/share/groff/%{version}/font/devdvi/HBTC
/usr/share/groff/%{version}/font/devdvi/HI
/usr/share/groff/%{version}/font/devdvi/HIEC
/usr/share/groff/%{version}/font/devdvi/HITC
/usr/share/groff/%{version}/font/devdvi/HR
/usr/share/groff/%{version}/font/devdvi/HREC
/usr/share/groff/%{version}/font/devdvi/HRTC
/usr/share/groff/%{version}/font/devdvi/MI
/usr/share/groff/%{version}/font/devdvi/S
/usr/share/groff/%{version}/font/devdvi/SA
/usr/share/groff/%{version}/font/devdvi/SB
/usr/share/groff/%{version}/font/devdvi/SC
/usr/share/groff/%{version}/font/devdvi/TB
/usr/share/groff/%{version}/font/devdvi/TBEC
/usr/share/groff/%{version}/font/devdvi/TBI
/usr/share/groff/%{version}/font/devdvi/TBIEC
/usr/share/groff/%{version}/font/devdvi/TBITC
/usr/share/groff/%{version}/font/devdvi/TBTC
/usr/share/groff/%{version}/font/devdvi/TI
/usr/share/groff/%{version}/font/devdvi/TIEC
/usr/share/groff/%{version}/font/devdvi/TITC
/usr/share/groff/%{version}/font/devdvi/TR
/usr/share/groff/%{version}/font/devdvi/TREC
/usr/share/groff/%{version}/font/devdvi/TRTC
/usr/share/groff/%{version}/font/devdvi/generate/CompileFonts
/usr/share/groff/%{version}/font/devdvi/generate/Makefile
/usr/share/groff/%{version}/font/devdvi/generate/ec.map
/usr/share/groff/%{version}/font/devdvi/generate/msam.map
/usr/share/groff/%{version}/font/devdvi/generate/msbm.map
/usr/share/groff/%{version}/font/devdvi/generate/tc.map
/usr/share/groff/%{version}/font/devdvi/generate/texb.map
/usr/share/groff/%{version}/font/devdvi/generate/texex.map
/usr/share/groff/%{version}/font/devdvi/generate/texi.map
/usr/share/groff/%{version}/font/devdvi/generate/texmi.map
/usr/share/groff/%{version}/font/devdvi/generate/texr.map
/usr/share/groff/%{version}/font/devdvi/generate/texsy.map
/usr/share/groff/%{version}/font/devdvi/generate/textex.map
/usr/share/groff/%{version}/font/devdvi/generate/textt.map
/usr/share/groff/%{version}/font/devhtml/B
/usr/share/groff/%{version}/font/devhtml/BI
/usr/share/groff/%{version}/font/devhtml/CB
/usr/share/groff/%{version}/font/devhtml/CBI
/usr/share/groff/%{version}/font/devhtml/CI
/usr/share/groff/%{version}/font/devhtml/CR
/usr/share/groff/%{version}/font/devhtml/DESC
/usr/share/groff/%{version}/font/devhtml/I
/usr/share/groff/%{version}/font/devhtml/R
/usr/share/groff/%{version}/font/devhtml/S
/usr/share/groff/%{version}/font/devlatin1/B
/usr/share/groff/%{version}/font/devlatin1/BI
/usr/share/groff/%{version}/font/devlatin1/DESC
/usr/share/groff/%{version}/font/devlatin1/I
/usr/share/groff/%{version}/font/devlatin1/R
/usr/share/groff/%{version}/font/devlbp/CB
/usr/share/groff/%{version}/font/devlbp/CI
/usr/share/groff/%{version}/font/devlbp/CR
/usr/share/groff/%{version}/font/devlbp/DESC
/usr/share/groff/%{version}/font/devlbp/EB
/usr/share/groff/%{version}/font/devlbp/EI
/usr/share/groff/%{version}/font/devlbp/ER
/usr/share/groff/%{version}/font/devlbp/HB
/usr/share/groff/%{version}/font/devlbp/HBI
/usr/share/groff/%{version}/font/devlbp/HI
/usr/share/groff/%{version}/font/devlbp/HNB
/usr/share/groff/%{version}/font/devlbp/HNBI
/usr/share/groff/%{version}/font/devlbp/HNI
/usr/share/groff/%{version}/font/devlbp/HNR
/usr/share/groff/%{version}/font/devlbp/HR
/usr/share/groff/%{version}/font/devlbp/TB
/usr/share/groff/%{version}/font/devlbp/TBI
/usr/share/groff/%{version}/font/devlbp/TI
/usr/share/groff/%{version}/font/devlbp/TR
/usr/share/groff/%{version}/font/devlj4/AB
/usr/share/groff/%{version}/font/devlj4/ABI
/usr/share/groff/%{version}/font/devlj4/AI
/usr/share/groff/%{version}/font/devlj4/ALBB
/usr/share/groff/%{version}/font/devlj4/ALBR
/usr/share/groff/%{version}/font/devlj4/AOB
/usr/share/groff/%{version}/font/devlj4/AOI
/usr/share/groff/%{version}/font/devlj4/AOR
/usr/share/groff/%{version}/font/devlj4/AR
/usr/share/groff/%{version}/font/devlj4/CB
/usr/share/groff/%{version}/font/devlj4/CBI
/usr/share/groff/%{version}/font/devlj4/CI
/usr/share/groff/%{version}/font/devlj4/CLARENDON
/usr/share/groff/%{version}/font/devlj4/CORONET
/usr/share/groff/%{version}/font/devlj4/CR
/usr/share/groff/%{version}/font/devlj4/DESC
/usr/share/groff/%{version}/font/devlj4/GB
/usr/share/groff/%{version}/font/devlj4/GBI
/usr/share/groff/%{version}/font/devlj4/GI
/usr/share/groff/%{version}/font/devlj4/GR
/usr/share/groff/%{version}/font/devlj4/LGB
/usr/share/groff/%{version}/font/devlj4/LGI
/usr/share/groff/%{version}/font/devlj4/LGR
/usr/share/groff/%{version}/font/devlj4/MARIGOLD
/usr/share/groff/%{version}/font/devlj4/OB
/usr/share/groff/%{version}/font/devlj4/OBI
/usr/share/groff/%{version}/font/devlj4/OI
/usr/share/groff/%{version}/font/devlj4/OR
/usr/share/groff/%{version}/font/devlj4/S
/usr/share/groff/%{version}/font/devlj4/SYMBOL
/usr/share/groff/%{version}/font/devlj4/TB
/usr/share/groff/%{version}/font/devlj4/TBI
/usr/share/groff/%{version}/font/devlj4/TI
/usr/share/groff/%{version}/font/devlj4/TNRB
/usr/share/groff/%{version}/font/devlj4/TNRBI
/usr/share/groff/%{version}/font/devlj4/TNRI
/usr/share/groff/%{version}/font/devlj4/TNRR
/usr/share/groff/%{version}/font/devlj4/TR
/usr/share/groff/%{version}/font/devlj4/UB
/usr/share/groff/%{version}/font/devlj4/UBI
/usr/share/groff/%{version}/font/devlj4/UCB
/usr/share/groff/%{version}/font/devlj4/UCBI
/usr/share/groff/%{version}/font/devlj4/UCI
/usr/share/groff/%{version}/font/devlj4/UCR
/usr/share/groff/%{version}/font/devlj4/UI
/usr/share/groff/%{version}/font/devlj4/UR
/usr/share/groff/%{version}/font/devlj4/WINGDINGS
/usr/share/groff/%{version}/font/devlj4/generate/Makefile
/usr/share/groff/%{version}/font/devlj4/generate/special.awk
/usr/share/groff/%{version}/font/devlj4/generate/special.map
/usr/share/groff/%{version}/font/devlj4/generate/symbol.map
/usr/share/groff/%{version}/font/devlj4/generate/text.map
/usr/share/groff/%{version}/font/devlj4/generate/wingdings.map
/usr/share/groff/%{version}/font/devpdf/CB
/usr/share/groff/%{version}/font/devpdf/CBI
/usr/share/groff/%{version}/font/devpdf/CI
/usr/share/groff/%{version}/font/devpdf/CR
/usr/share/groff/%{version}/font/devpdf/DESC
/usr/share/groff/%{version}/font/devpdf/EURO
/usr/share/groff/%{version}/font/devpdf/Foundry
/usr/share/groff/%{version}/font/devpdf/HB
/usr/share/groff/%{version}/font/devpdf/HBI
/usr/share/groff/%{version}/font/devpdf/HI
/usr/share/groff/%{version}/font/devpdf/HR
/usr/share/groff/%{version}/font/devpdf/S
/usr/share/groff/%{version}/font/devpdf/TB
/usr/share/groff/%{version}/font/devpdf/TBI
/usr/share/groff/%{version}/font/devpdf/TI
/usr/share/groff/%{version}/font/devpdf/TR
/usr/share/groff/%{version}/font/devpdf/ZD
/usr/share/groff/%{version}/font/devpdf/download
/usr/share/groff/%{version}/font/devpdf/enc/text.enc
/usr/share/groff/%{version}/font/devpdf/map/dingbats.map
/usr/share/groff/%{version}/font/devpdf/map/symbolchars
/usr/share/groff/%{version}/font/devpdf/map/symbolmap
/usr/share/groff/%{version}/font/devpdf/map/textmap
/usr/share/groff/%{version}/font/devps/AB
/usr/share/groff/%{version}/font/devps/ABI
/usr/share/groff/%{version}/font/devps/AI
/usr/share/groff/%{version}/font/devps/AR
/usr/share/groff/%{version}/font/devps/BMB
/usr/share/groff/%{version}/font/devps/BMBI
/usr/share/groff/%{version}/font/devps/BMI
/usr/share/groff/%{version}/font/devps/BMR
/usr/share/groff/%{version}/font/devps/CB
/usr/share/groff/%{version}/font/devps/CBI
/usr/share/groff/%{version}/font/devps/CI
/usr/share/groff/%{version}/font/devps/CR
/usr/share/groff/%{version}/font/devps/DESC
/usr/share/groff/%{version}/font/devps/EURO
/usr/share/groff/%{version}/font/devps/HB
/usr/share/groff/%{version}/font/devps/HBI
/usr/share/groff/%{version}/font/devps/HI
/usr/share/groff/%{version}/font/devps/HNB
/usr/share/groff/%{version}/font/devps/HNBI
/usr/share/groff/%{version}/font/devps/HNI
/usr/share/groff/%{version}/font/devps/HNR
/usr/share/groff/%{version}/font/devps/HR
/usr/share/groff/%{version}/font/devps/NB
/usr/share/groff/%{version}/font/devps/NBI
/usr/share/groff/%{version}/font/devps/NI
/usr/share/groff/%{version}/font/devps/NR
/usr/share/groff/%{version}/font/devps/PB
/usr/share/groff/%{version}/font/devps/PBI
/usr/share/groff/%{version}/font/devps/PI
/usr/share/groff/%{version}/font/devps/PR
/usr/share/groff/%{version}/font/devps/S
/usr/share/groff/%{version}/font/devps/SS
/usr/share/groff/%{version}/font/devps/TB
/usr/share/groff/%{version}/font/devps/TBI
/usr/share/groff/%{version}/font/devps/TI
/usr/share/groff/%{version}/font/devps/TR
/usr/share/groff/%{version}/font/devps/ZCMI
/usr/share/groff/%{version}/font/devps/ZD
/usr/share/groff/%{version}/font/devps/ZDR
/usr/share/groff/%{version}/font/devps/download
/usr/share/groff/%{version}/font/devps/freeeuro.afm
/usr/share/groff/%{version}/font/devps/freeeuro.pfa
/usr/share/groff/%{version}/font/devps/generate/Makefile
/usr/share/groff/%{version}/font/devps/generate/afmname
/usr/share/groff/%{version}/font/devps/generate/dingbats.map
/usr/share/groff/%{version}/font/devps/generate/dingbats.rmap
/usr/share/groff/%{version}/font/devps/generate/lgreekmap
/usr/share/groff/%{version}/font/devps/generate/symbol.sed
/usr/share/groff/%{version}/font/devps/generate/symbolchars
/usr/share/groff/%{version}/font/devps/generate/symbolsl.afm
/usr/share/groff/%{version}/font/devps/generate/textmap
/usr/share/groff/%{version}/font/devps/prologue
/usr/share/groff/%{version}/font/devps/symbolsl.pfa
/usr/share/groff/%{version}/font/devps/text.enc
/usr/share/groff/%{version}/font/devps/zapfdr.pfa
/usr/share/groff/%{version}/font/devutf8/B
/usr/share/groff/%{version}/font/devutf8/BI
/usr/share/groff/%{version}/font/devutf8/DESC
/usr/share/groff/%{version}/font/devutf8/I
/usr/share/groff/%{version}/font/devutf8/R
/usr/share/groff/%{version}/oldfont/devps/CB
/usr/share/groff/%{version}/oldfont/devps/CBI
/usr/share/groff/%{version}/oldfont/devps/CI
/usr/share/groff/%{version}/oldfont/devps/CR
/usr/share/groff/%{version}/oldfont/devps/HB
/usr/share/groff/%{version}/oldfont/devps/HBI
/usr/share/groff/%{version}/oldfont/devps/HI
/usr/share/groff/%{version}/oldfont/devps/HNB
/usr/share/groff/%{version}/oldfont/devps/HNBI
/usr/share/groff/%{version}/oldfont/devps/HNI
/usr/share/groff/%{version}/oldfont/devps/HNR
/usr/share/groff/%{version}/oldfont/devps/HR
/usr/share/groff/%{version}/oldfont/devps/NB
/usr/share/groff/%{version}/oldfont/devps/NBI
/usr/share/groff/%{version}/oldfont/devps/NI
/usr/share/groff/%{version}/oldfont/devps/NR
/usr/share/groff/%{version}/oldfont/devps/PB
/usr/share/groff/%{version}/oldfont/devps/PBI
/usr/share/groff/%{version}/oldfont/devps/PI
/usr/share/groff/%{version}/oldfont/devps/PR
/usr/share/groff/%{version}/oldfont/devps/S
/usr/share/groff/%{version}/oldfont/devps/SS
/usr/share/groff/%{version}/oldfont/devps/TB
/usr/share/groff/%{version}/oldfont/devps/TBI
/usr/share/groff/%{version}/oldfont/devps/TI
/usr/share/groff/%{version}/oldfont/devps/TR
/usr/share/groff/%{version}/oldfont/devps/symbol.afm
/usr/share/groff/%{version}/oldfont/devps/symbolsl.afm
/usr/share/groff/%{version}/oldfont/devps/zapfdr.afm
/usr/share/groff/%{version}/oldfont/devps/zapfdr.ps
/usr/share/groff/%{version}/pic/chem.pic
/usr/share/groff/%{version}/tmac/62bit.tmac
/usr/share/groff/%{version}/tmac/X.tmac
/usr/share/groff/%{version}/tmac/Xps.tmac
/usr/share/groff/%{version}/tmac/a4.tmac
/usr/share/groff/%{version}/tmac/an-ext.tmac
/usr/share/groff/%{version}/tmac/an-old.tmac
/usr/share/groff/%{version}/tmac/an.tmac
/usr/share/groff/%{version}/tmac/andoc.tmac
/usr/share/groff/%{version}/tmac/composite.tmac
/usr/share/groff/%{version}/tmac/cp1047.tmac
/usr/share/groff/%{version}/tmac/cs.tmac
/usr/share/groff/%{version}/tmac/de.tmac
/usr/share/groff/%{version}/tmac/den.tmac
/usr/share/groff/%{version}/tmac/devtag.tmac
/usr/share/groff/%{version}/tmac/doc-old.tmac
/usr/share/groff/%{version}/tmac/doc.tmac
/usr/share/groff/%{version}/tmac/dvi.tmac
/usr/share/groff/%{version}/tmac/e.tmac
/usr/share/groff/%{version}/tmac/ec.tmac
/usr/share/groff/%{version}/tmac/eqnrc
/usr/share/groff/%{version}/tmac/europs.tmac
/usr/share/groff/%{version}/tmac/fallbacks.tmac
/usr/share/groff/%{version}/tmac/fr.tmac
/usr/share/groff/%{version}/tmac/hdmisc.tmac
/usr/share/groff/%{version}/tmac/hdtbl.tmac
/usr/share/groff/%{version}/tmac/html-end.tmac
/usr/share/groff/%{version}/tmac/html.tmac
/usr/share/groff/%{version}/tmac/hyphen.cs
/usr/share/groff/%{version}/tmac/hyphen.den
/usr/share/groff/%{version}/tmac/hyphen.det
/usr/share/groff/%{version}/tmac/hyphen.fr
/usr/share/groff/%{version}/tmac/hyphen.sv
/usr/share/groff/%{version}/tmac/hyphen.us
/usr/share/groff/%{version}/tmac/hyphenex.cs
/usr/share/groff/%{version}/tmac/hyphenex.us
/usr/share/groff/%{version}/tmac/ja.tmac
/usr/share/groff/%{version}/tmac/latin1.tmac
/usr/share/groff/%{version}/tmac/latin2.tmac
/usr/share/groff/%{version}/tmac/latin5.tmac
/usr/share/groff/%{version}/tmac/latin9.tmac
/usr/share/groff/%{version}/tmac/lbp.tmac
/usr/share/groff/%{version}/tmac/lj4.tmac
/usr/share/groff/%{version}/tmac/m.tmac
/usr/share/groff/%{version}/tmac/man.tmac
/usr/share/groff/%{version}/tmac/mandoc.tmac
/usr/share/groff/%{version}/tmac/mdoc.tmac
/usr/share/groff/%{version}/tmac/mdoc/doc-common
/usr/share/groff/%{version}/tmac/mdoc/doc-ditroff
/usr/share/groff/%{version}/tmac/mdoc/doc-nroff
/usr/share/groff/%{version}/tmac/mdoc/doc-syms
/usr/share/groff/%{version}/tmac/me.tmac
/usr/share/groff/%{version}/tmac/mm.tmac
/usr/share/groff/%{version}/tmac/mm/0.MT
/usr/share/groff/%{version}/tmac/mm/4.MT
/usr/share/groff/%{version}/tmac/mm/5.MT
/usr/share/groff/%{version}/tmac/mm/locale
/usr/share/groff/%{version}/tmac/mm/ms.cov
/usr/share/groff/%{version}/tmac/mm/se_locale
/usr/share/groff/%{version}/tmac/mm/se_ms.cov
/usr/share/groff/%{version}/tmac/mmse.tmac
/usr/share/groff/%{version}/tmac/mom.tmac
/usr/share/groff/%{version}/tmac/ms.tmac
/usr/share/groff/%{version}/tmac/mse.tmac
/usr/share/groff/%{version}/tmac/om.tmac
/usr/share/groff/%{version}/tmac/papersize.tmac
/usr/share/groff/%{version}/tmac/pdf.tmac
/usr/share/groff/%{version}/tmac/pdfmark.tmac
/usr/share/groff/%{version}/tmac/pdfpic.tmac
/usr/share/groff/%{version}/tmac/pic.tmac
/usr/share/groff/%{version}/tmac/ps.tmac
/usr/share/groff/%{version}/tmac/psatk.tmac
/usr/share/groff/%{version}/tmac/psold.tmac
/usr/share/groff/%{version}/tmac/pspic.tmac
/usr/share/groff/%{version}/tmac/refer-me.tmac
/usr/share/groff/%{version}/tmac/refer-mm.tmac
/usr/share/groff/%{version}/tmac/refer-ms.tmac
/usr/share/groff/%{version}/tmac/refer.tmac
/usr/share/groff/%{version}/tmac/s.tmac
/usr/share/groff/%{version}/tmac/safer.tmac
/usr/share/groff/%{version}/tmac/spdf.tmac
/usr/share/groff/%{version}/tmac/sv.tmac
/usr/share/groff/%{version}/tmac/trace.tmac
/usr/share/groff/%{version}/tmac/trans.tmac
/usr/share/groff/%{version}/tmac/troffrc
/usr/share/groff/%{version}/tmac/troffrc-end
/usr/share/groff/%{version}/tmac/tty-char.tmac
/usr/share/groff/%{version}/tmac/tty.tmac
/usr/share/groff/%{version}/tmac/unicode.tmac
/usr/share/groff/%{version}/tmac/www.tmac
/usr/share/groff/%{version}/tmac/zh.tmac
/usr/share/groff/current
/usr/share/groff/site-tmac/man.local
/usr/share/groff/site-tmac/mdoc.local
/usr/share/info/groff.info-1.gz
/usr/share/info/groff.info-2.gz
/usr/share/info/groff.info.gz
/usr/share/man/man1/addftinfo.1.gz
/usr/share/man/man1/afmtodit.1.gz
/usr/share/man/man1/chem.1.gz
/usr/share/man/man1/eqn.1.gz
/usr/share/man/man1/eqn2graph.1.gz
/usr/share/man/man1/gdiffmk.1.gz
/usr/share/man/man1/glilypond.1.gz
/usr/share/man/man1/gperl.1.gz
/usr/share/man/man1/gpinyin.1.gz
/usr/share/man/man1/grap2graph.1.gz
/usr/share/man/man1/grn.1.gz
/usr/share/man/man1/grodvi.1.gz
/usr/share/man/man1/groff.1.gz
/usr/share/man/man1/groffer.1.gz
/usr/share/man/man1/grog.1.gz
/usr/share/man/man1/grohtml.1.gz
/usr/share/man/man1/grolbp.1.gz
/usr/share/man/man1/grolj4.1.gz
/usr/share/man/man1/gropdf.1.gz
/usr/share/man/man1/grops.1.gz
/usr/share/man/man1/grotty.1.gz
/usr/share/man/man1/hpftodit.1.gz
/usr/share/man/man1/indxbib.1.gz
/usr/share/man/man1/lkbib.1.gz
/usr/share/man/man1/lookbib.1.gz
/usr/share/man/man1/mmroff.1.gz
/usr/share/man/man1/neqn.1.gz
/usr/share/man/man1/nroff.1.gz
/usr/share/man/man1/pdfmom.1.gz
/usr/share/man/man1/pdfroff.1.gz
/usr/share/man/man1/pfbtops.1.gz
/usr/share/man/man1/pic.1.gz
/usr/share/man/man1/pic2graph.1.gz
/usr/share/man/man1/preconv.1.gz
/usr/share/man/man1/refer.1.gz
/usr/share/man/man1/roff2dvi.1.gz
/usr/share/man/man1/roff2html.1.gz
/usr/share/man/man1/roff2pdf.1.gz
/usr/share/man/man1/roff2ps.1.gz
/usr/share/man/man1/roff2text.1.gz
/usr/share/man/man1/roff2x.1.gz
/usr/share/man/man1/soelim.1.gz
/usr/share/man/man1/tbl.1.gz
/usr/share/man/man1/tfmtodit.1.gz
/usr/share/man/man1/troff.1.gz
/usr/share/man/man5/groff_filenames.5.gz
/usr/share/man/man5/groff_font.5.gz
/usr/share/man/man5/groff_out.5.gz
/usr/share/man/man5/groff_tmac.5.gz
/usr/share/man/man5/lj4_font.5.gz
/usr/share/man/man7/ditroff.7.gz
/usr/share/man/man7/groff.7.gz
/usr/share/man/man7/groff_char.7.gz
/usr/share/man/man7/groff_diff.7.gz
/usr/share/man/man7/groff_hdtbl.7.gz
/usr/share/man/man7/groff_man.7.gz
/usr/share/man/man7/groff_mdoc.7.gz
/usr/share/man/man7/groff_me.7.gz
/usr/share/man/man7/groff_mm.7.gz
/usr/share/man/man7/groff_mmse.7.gz
/usr/share/man/man7/groff_mom.7.gz
/usr/share/man/man7/groff_ms.7.gz
/usr/share/man/man7/groff_trace.7.gz
/usr/share/man/man7/groff_www.7.gz
/usr/share/man/man7/roff.7.gz
/usr/share/doc/groff-1.22.4/examples/mom/letter.pdf
/usr/share/doc/groff-1.22.4/examples/mom/mom-pdf.pdf
/usr/share/doc/groff-1.22.4/examples/mom/mon_premier_doc.pdf
/usr/share/doc/groff-1.22.4/examples/mom/sample_docs.pdf
/usr/share/doc/groff-1.22.4/examples/mom/slide-demo.pdf
/usr/share/doc/groff-1.22.4/examples/mom/typesetting.pdf
/usr/share/doc/groff-1.22.4/pdf/automake.pdf
/usr/share/doc/groff-1.22.4/pdf/mom-pdf.pdf
/usr/share/doc/groff-1.22.4/pdf/pdfmark.pdf
/usr/share/groff/1.22.4/font/devpdf/AB
/usr/share/groff/1.22.4/font/devpdf/ABI
/usr/share/groff/1.22.4/font/devpdf/AI
/usr/share/groff/1.22.4/font/devpdf/AR
/usr/share/groff/1.22.4/font/devpdf/BMB
/usr/share/groff/1.22.4/font/devpdf/BMBI
/usr/share/groff/1.22.4/font/devpdf/BMI
/usr/share/groff/1.22.4/font/devpdf/BMR
/usr/share/groff/1.22.4/font/devpdf/HNB
/usr/share/groff/1.22.4/font/devpdf/HNBI
/usr/share/groff/1.22.4/font/devpdf/HNI
/usr/share/groff/1.22.4/font/devpdf/HNR
/usr/share/groff/1.22.4/font/devpdf/NB
/usr/share/groff/1.22.4/font/devpdf/NBI
/usr/share/groff/1.22.4/font/devpdf/NI
/usr/share/groff/1.22.4/font/devpdf/NR
/usr/share/groff/1.22.4/font/devpdf/PB
/usr/share/groff/1.22.4/font/devpdf/PBI
/usr/share/groff/1.22.4/font/devpdf/PI
/usr/share/groff/1.22.4/font/devpdf/PR
/usr/share/groff/1.22.4/font/devpdf/U-AB
/usr/share/groff/1.22.4/font/devpdf/U-ABI
/usr/share/groff/1.22.4/font/devpdf/U-AI
/usr/share/groff/1.22.4/font/devpdf/U-AR
/usr/share/groff/1.22.4/font/devpdf/U-BMB
/usr/share/groff/1.22.4/font/devpdf/U-BMBI
/usr/share/groff/1.22.4/font/devpdf/U-BMI
/usr/share/groff/1.22.4/font/devpdf/U-BMR
/usr/share/groff/1.22.4/font/devpdf/U-CB
/usr/share/groff/1.22.4/font/devpdf/U-CBI
/usr/share/groff/1.22.4/font/devpdf/U-CI
/usr/share/groff/1.22.4/font/devpdf/U-CR
/usr/share/groff/1.22.4/font/devpdf/U-HB
/usr/share/groff/1.22.4/font/devpdf/U-HBI
/usr/share/groff/1.22.4/font/devpdf/U-HI
/usr/share/groff/1.22.4/font/devpdf/U-HNB
/usr/share/groff/1.22.4/font/devpdf/U-HNBI
/usr/share/groff/1.22.4/font/devpdf/U-HNI
/usr/share/groff/1.22.4/font/devpdf/U-HNR
/usr/share/groff/1.22.4/font/devpdf/U-HR
/usr/share/groff/1.22.4/font/devpdf/U-NB
/usr/share/groff/1.22.4/font/devpdf/U-NBI
/usr/share/groff/1.22.4/font/devpdf/U-NI
/usr/share/groff/1.22.4/font/devpdf/U-NR
/usr/share/groff/1.22.4/font/devpdf/U-PB
/usr/share/groff/1.22.4/font/devpdf/U-PBI
/usr/share/groff/1.22.4/font/devpdf/U-PI
/usr/share/groff/1.22.4/font/devpdf/U-PR
/usr/share/groff/1.22.4/font/devpdf/U-S
/usr/share/groff/1.22.4/font/devpdf/U-TB
/usr/share/groff/1.22.4/font/devpdf/U-TBI
/usr/share/groff/1.22.4/font/devpdf/U-TI
/usr/share/groff/1.22.4/font/devpdf/U-TR
/usr/share/groff/1.22.4/font/devpdf/U-ZCMI
/usr/share/groff/1.22.4/font/devpdf/U-ZD
/usr/share/groff/1.22.4/font/devpdf/ZCMI


%changelog
* Tue May 31 2016 Adam Miller <maxamillion@fedoraproject.org>
-

# see /usr/libexec/rpm/macros for macros
