Name:           openrc
Version:	0.45.1
Release:        1%{?dist}
Summary:	OpenRC manages the services, startup and shutdown of a host

License:	BDS-2
URL:		https://packages.gentoo.org/packages/sys-apps/openrc
Source0:	https://github.com/OpenRC/openrc/archive/refs/tags/%{version}.tar.gz

#BuildRequires:
#Requires:

%description
OpenRC manages the services, startup and shutdown of a host

%prep
%setup -q

%build
meson build

%install
rm -rf %{buildroot}
cd build
DESTDIR=%{buildroot} meson install
%{__rm} -f %{buildroot}/usr/share/info/dir

#%post
#/sbin/ldconfig
#/sbin/install-info /usr/share/info/DevIL_manual.info.gz /usr/share/info/dir 2> /dev/null || :

#%postun
#/sbin/ldconfig
#/sbin/install-info --delete /usr/share/info/DevIL_manual.info.gz /usr/share/info/dir 2> /dev/null || :

%files
/bin/rc-status
/etc/conf.d/agetty
/etc/conf.d/bootmisc
/etc/conf.d/consolefont
/etc/conf.d/devfs
/etc/conf.d/dmesg
/etc/conf.d/fsck
/etc/conf.d/hostname
/etc/conf.d/hwclock
/etc/conf.d/keymaps
/etc/conf.d/killprocs
/etc/conf.d/localmount
/etc/conf.d/modules
/etc/conf.d/mtab
/etc/conf.d/net-online
/etc/conf.d/netmount
/etc/conf.d/network
/etc/conf.d/seedrng
/etc/conf.d/staticroute
/etc/conf.d/swap
/etc/init.d/agetty
/etc/init.d/binfmt
/etc/init.d/bootmisc
/etc/init.d/cgroups
/etc/init.d/consolefont
/etc/init.d/devfs
/etc/init.d/dmesg
/etc/init.d/fsck
/etc/init.d/functions.sh
/etc/init.d/hostname
/etc/init.d/hwclock
/etc/init.d/keymaps
/etc/init.d/killprocs
/etc/init.d/local
/etc/init.d/localmount
/etc/init.d/loopback
/etc/init.d/modules
/etc/init.d/mount-ro
/etc/init.d/mtab
/etc/init.d/net-online
/etc/init.d/netmount
/etc/init.d/network
/etc/init.d/numlock
/etc/init.d/osclock
/etc/init.d/procfs
/etc/init.d/root
/etc/init.d/runsvdir
/etc/init.d/s6-svscan
/etc/init.d/save-keymaps
/etc/init.d/save-termencoding
/etc/init.d/savecache
/etc/init.d/seedrng
/etc/init.d/staticroute
/etc/init.d/swap
/etc/init.d/swclock
/etc/init.d/sysctl
/etc/init.d/sysfs
/etc/init.d/termencoding
/etc/local.d/README
/etc/pam.d/start-stop-daemon
/etc/pam.d/supervise-daemon
/etc/rc.conf
/etc/runlevels/boot/binfmt
/etc/runlevels/boot/bootmisc
/etc/runlevels/boot/fsck
/etc/runlevels/boot/hostname
/etc/runlevels/boot/hwclock
/etc/runlevels/boot/keymaps
/etc/runlevels/boot/localmount
/etc/runlevels/boot/loopback
/etc/runlevels/boot/modules
/etc/runlevels/boot/mtab
/etc/runlevels/boot/network
/etc/runlevels/boot/procfs
/etc/runlevels/boot/root
/etc/runlevels/boot/save-keymaps
/etc/runlevels/boot/save-termencoding
/etc/runlevels/boot/seedrng
/etc/runlevels/boot/staticroute
/etc/runlevels/boot/swap
/etc/runlevels/boot/sysctl
/etc/runlevels/boot/termencoding
/etc/runlevels/default/local
/etc/runlevels/default/netmount
/etc/runlevels/nonetwork/local
/etc/runlevels/shutdown/killprocs
/etc/runlevels/shutdown/mount-ro
/etc/runlevels/shutdown/savecache
/etc/runlevels/sysinit/cgroups
/etc/runlevels/sysinit/devfs
/etc/runlevels/sysinit/dmesg
/etc/runlevels/sysinit/sysfs
/etc/sysctl.d/README
/lib/rc/bin/checkpath
/lib/rc/bin/ebegin
/lib/rc/bin/eend
/lib/rc/bin/eerror
/lib/rc/bin/eerrorn
/lib/rc/bin/eindent
/lib/rc/bin/einfo
/lib/rc/bin/einfon
/lib/rc/bin/eoutdent
/lib/rc/bin/esyslog
/lib/rc/bin/eval_ecolors
/lib/rc/bin/ewaitfile
/lib/rc/bin/ewarn
/lib/rc/bin/ewarnn
/lib/rc/bin/ewend
/lib/rc/bin/fstabinfo
/lib/rc/bin/get_options
/lib/rc/bin/is_newer_than
/lib/rc/bin/is_older_than
/lib/rc/bin/kill_all
/lib/rc/bin/mountinfo
/lib/rc/bin/on_ac_power
/lib/rc/bin/rc-depend
/lib/rc/bin/save_options
/lib/rc/bin/service_crashed
/lib/rc/bin/service_get_value
/lib/rc/bin/service_hotplugged
/lib/rc/bin/service_inactive
/lib/rc/bin/service_set_value
/lib/rc/bin/service_started
/lib/rc/bin/service_started_daemon
/lib/rc/bin/service_starting
/lib/rc/bin/service_stopped
/lib/rc/bin/service_stopping
/lib/rc/bin/service_wasinactive
/lib/rc/bin/shell_var
/lib/rc/bin/vebegin
/lib/rc/bin/veend
/lib/rc/bin/veindent
/lib/rc/bin/veinfo
/lib/rc/bin/veoutdent
/lib/rc/bin/vewarn
/lib/rc/bin/vewend
/lib/rc/sbin/mark_service_crashed
/lib/rc/sbin/mark_service_failed
/lib/rc/sbin/mark_service_hotplugged
/lib/rc/sbin/mark_service_inactive
/lib/rc/sbin/mark_service_started
/lib/rc/sbin/mark_service_starting
/lib/rc/sbin/mark_service_stopped
/lib/rc/sbin/mark_service_stopping
/lib/rc/sbin/mark_service_wasinactive
/lib/rc/sbin/rc-abort
/lib/rc/sbin/seedrng
/lib/rc/sbin/swclock
/lib/rc/sh/binfmt.sh
/lib/rc/sh/cgroup-release-agent.sh
/lib/rc/sh/functions.sh
/lib/rc/sh/gendepends.sh
/lib/rc/sh/init-early.sh
/lib/rc/sh/init.sh
/lib/rc/sh/openrc-run.sh
/lib/rc/sh/rc-cgroup.sh
/lib/rc/sh/rc-functions.sh
/lib/rc/sh/rc-mount.sh
/lib/rc/sh/runit.sh
/lib/rc/sh/s6.sh
/lib/rc/sh/start-stop-daemon.sh
/lib/rc/sh/supervise-daemon.sh
/lib/rc/version
/lib64/libeinfo.so
/lib64/libeinfo.so.1
/lib64/librc.so
/lib64/librc.so.1
/sbin/openrc
/sbin/openrc-init
/sbin/openrc-run
/sbin/openrc-shutdown
/sbin/rc
/sbin/rc-service
/sbin/rc-sstat
/sbin/rc-update
/sbin/runscript
/sbin/start-stop-daemon
/sbin/supervise-daemon
/usr/include/einfo.h
/usr/include/rc.h
/usr/lib64/pkgconfig/einfo.pc
/usr/lib64/pkgconfig/openrc.pc
/usr/share/bash-completion/completions/openrc
/usr/share/bash-completion/completions/openrc-service-script
/usr/share/bash-completion/completions/rc-service
/usr/share/bash-completion/completions/rc-status
/usr/share/bash-completion/completions/rc-update
/usr/share/man/man3/ebegin.3.gz
/usr/share/man/man3/ebeginn.3.gz
/usr/share/man/man3/ebeginv.3.gz
/usr/share/man/man3/ebeginvn.3.gz
/usr/share/man/man3/ebracket.3.gz
/usr/share/man/man3/eend.3.gz
/usr/share/man/man3/eendv.3.gz
/usr/share/man/man3/eerror.3.gz
/usr/share/man/man3/eerrorn.3.gz
/usr/share/man/man3/eerrorx.3.gz
/usr/share/man/man3/eindent.3.gz
/usr/share/man/man3/eindentv.3.gz
/usr/share/man/man3/einfo.3.gz
/usr/share/man/man3/einfon.3.gz
/usr/share/man/man3/einfov.3.gz
/usr/share/man/man3/einfovn.3.gz
/usr/share/man/man3/eoutdent.3.gz
/usr/share/man/man3/eoutdentv.3.gz
/usr/share/man/man3/eprefix.3.gz
/usr/share/man/man3/ewarn.3.gz
/usr/share/man/man3/ewarnn.3.gz
/usr/share/man/man3/ewarnv.3.gz
/usr/share/man/man3/ewarnvn.3.gz
/usr/share/man/man3/ewarnx.3.gz
/usr/share/man/man3/ewend.3.gz
/usr/share/man/man3/ewendv.3.gz
/usr/share/man/man3/rc_config.3.gz
/usr/share/man/man3/rc_config_list.3.gz
/usr/share/man/man3/rc_config_load.3.gz
/usr/share/man/man3/rc_config_value.3.gz
/usr/share/man/man3/rc_deptree.3.gz
/usr/share/man/man3/rc_deptree_depend.3.gz
/usr/share/man/man3/rc_deptree_depends.3.gz
/usr/share/man/man3/rc_deptree_free.3.gz
/usr/share/man/man3/rc_deptree_load.3.gz
/usr/share/man/man3/rc_deptree_order.3.gz
/usr/share/man/man3/rc_deptree_update.3.gz
/usr/share/man/man3/rc_deptree_update_needed.3.gz
/usr/share/man/man3/rc_find_pids.3.gz
/usr/share/man/man3/rc_plugin_hook.3.gz
/usr/share/man/man3/rc_runlevel.3.gz
/usr/share/man/man3/rc_runlevel_exists.3.gz
/usr/share/man/man3/rc_runlevel_get.3.gz
/usr/share/man/man3/rc_runlevel_list.3.gz
/usr/share/man/man3/rc_runlevel_set.3.gz
/usr/share/man/man3/rc_runlevel_starting.3.gz
/usr/share/man/man3/rc_runlevel_stopping.3.gz
/usr/share/man/man3/rc_service.3.gz
/usr/share/man/man3/rc_service_add.3.gz
/usr/share/man/man3/rc_service_daemon_set.3.gz
/usr/share/man/man3/rc_service_daemons_crashed.3.gz
/usr/share/man/man3/rc_service_delete.3.gz
/usr/share/man/man3/rc_service_description.3.gz
/usr/share/man/man3/rc_service_exists.3.gz
/usr/share/man/man3/rc_service_extra_commands.3.gz
/usr/share/man/man3/rc_service_in_runlevel.3.gz
/usr/share/man/man3/rc_service_mark.3.gz
/usr/share/man/man3/rc_service_plugable.3.gz
/usr/share/man/man3/rc_service_resolve.3.gz
/usr/share/man/man3/rc_service_schedule_clear.3.gz
/usr/share/man/man3/rc_service_schedule_start.3.gz
/usr/share/man/man3/rc_service_started_daemon.3.gz
/usr/share/man/man3/rc_service_state.3.gz
/usr/share/man/man3/rc_service_value_get.3.gz
/usr/share/man/man3/rc_service_value_set.3.gz
/usr/share/man/man3/rc_services_in_runlevel.3.gz
/usr/share/man/man3/rc_services_in_state.3.gz
/usr/share/man/man3/rc_services_scheduled.3.gz
/usr/share/man/man3/rc_services_scheduled_by.3.gz
/usr/share/man/man3/rc_stringlist.3.gz
/usr/share/man/man3/rc_stringlist_add.3.gz
/usr/share/man/man3/rc_stringlist_addu.3.gz
/usr/share/man/man3/rc_stringlist_delete.3.gz
/usr/share/man/man3/rc_stringlist_free.3.gz
/usr/share/man/man3/rc_stringlist_new.3.gz
/usr/share/man/man3/rc_stringlist_sort.3.gz
/usr/share/man/man3/rc_yesno.3.gz
/usr/share/man/man8/openrc-init.8.gz
/usr/share/man/man8/openrc-run.8.gz
/usr/share/man/man8/openrc-shutdown.8.gz
/usr/share/man/man8/openrc.8.gz
/usr/share/man/man8/rc-service.8.gz
/usr/share/man/man8/rc-sstat.8.gz
/usr/share/man/man8/rc-status.8.gz
/usr/share/man/man8/rc-update.8.gz
/usr/share/man/man8/start-stop-daemon.8.gz
/usr/share/man/man8/supervise-daemon.8.gz
/usr/share/openrc/support/deptree2dot/README.md
/usr/share/openrc/support/deptree2dot/deptree2dot
/usr/share/openrc/support/init.d.examples/README.md
/usr/share/openrc/support/init.d.examples/avahi-dnsconfd
/usr/share/openrc/support/init.d.examples/avahid
/usr/share/openrc/support/init.d.examples/dbus
/usr/share/openrc/support/init.d.examples/dhcpcd
/usr/share/openrc/support/init.d.examples/hald
/usr/share/openrc/support/init.d.examples/named
/usr/share/openrc/support/init.d.examples/ntpd
/usr/share/openrc/support/init.d.examples/openvpn
/usr/share/openrc/support/init.d.examples/polkitd
/usr/share/openrc/support/init.d.examples/sshd
/usr/share/openrc/support/init.d.examples/wpa_supplicant
/usr/share/openrc/support/openvpn/README.md
/usr/share/openrc/support/openvpn/down.sh
/usr/share/openrc/support/openvpn/up.sh
/usr/share/openrc/support/sysvinit/README.md
/usr/share/openrc/support/sysvinit/halt.sh
/usr/share/openrc/support/sysvinit/inittab
/usr/share/zsh/site-functions/_openrc
/usr/share/zsh/site-functions/_rc-service
/usr/share/zsh/site-functions/_rc-status
/usr/share/zsh/site-functions/_rc-update

%doc

%changelog
